### PR TITLE
Project - Emma Pérez 

### PR DESCRIPTION
**Pull request by emma-prz**

### CODE REVIEW

**Comment by Enchufa2** [comment]
Is the post ready? You only commited the Rmd and the html files. The whole `_projects` folder, with all files inside, should be commited.

**Comment by emma-prz** [comment]
> Is the post ready? You only commited the Rmd and the html files. The whole `_projects` folder, with all files inside, should be commited.

I think is all commited now (everything inside the projects folder with my NIA is commited)

**Review by Enchufa2 — APPROVED** [review]
Amazing work! Merging with minor tweaks.

**Comment by Enchufa2** [comment]
Here you go: https://csslab.uc3m.es/dataviz/projects/2022/100392586/

**Comment by emma-prz** [comment]
> Amazing work! Merging with minor tweaks.

Thanks Iñaki for the tweaks! It looks much better now

**Pull request merged**
