### PR TITLE
Patch 1 - Modifications

### PR DESCRIPTION
**Pull request by SofiaVillamil**

### CODE REVIEW

**Comment by SofiaVillamil** [comment]
All modifications done, it is up for review

**Comment by Enchufa2** [comment]
There was no need to open a new branch and a new pull request. Could you please merge this into main and push?

**Comment by SofiaVillamil** [comment]
I am sorry. I think I fixed it. Is it okey now?

**Comment by Enchufa2** [comment]
Great, closing this one.

**Pull request closed without merging**
