### PR TITLE
Project - Pablo Arroyo

### PR DESCRIPTION
**Pull request by arroyo-pablo**
This is the project for Data Visualization of Pablo Arroyo.

### CODE REVIEW

**Comment by Enchufa2** [comment]
Great work! Minor thing: wouldn't it be better to set `out.width="100%"` in order for the images to take advantage of the whole text width? Also, please add and commit the path `projects/2022/100483607` (without the `_`) too.

**Comment by arroyo-pablo** [comment]
Hi Iñaki,
I just added the modifications that you told me in the previous comment. However, I couldn't manage to add the path project/2022/…. It appears to be in another directory, and I do not know how to add it to my current project of R.Markdown, which is established in the “_project” instead of just “project” .
Thank you, Pablo.

**Comment by Enchufa2** [comment]
You mean you created a new RStudio project inside the `dataviz/_projects` directory? You need to open the `dataviz/dataviz.Rproj` file, which will set the proper working directory, and then you should be able to add both project directories.

**Comment by arroyo-pablo** [comment]
Nono, I didn´t create a new RStudio project, is just the same that I created on the tutorial on which I´ve been working.
And if you observe the tutorial, in the last steps about "Commiting and punish the changes", in my GitHub I observe the same files as in the tutorial, just _projetcs/2022/100xxxxx/
It is hard to explain that from here, because I am not understand a lot about this field.
Thank you and sorry, Pablo.

**Comment by Enchufa2** [comment]
Apologies, I messed up the PR. Can you open the project and push again to your repo?

**Comment by Enchufa2** [comment]
If this doesn't work, go to [your repo's](https://github.com/arroyo-pablo/dataviz) settings tab and add me as a collaborator in the "Collaborators and teams" submenu, and I'll handle it.

**Pull request closed without merging**
