### PR TITLE
Project - Gabriel Rodríguez Molina

### PR DESCRIPTION
**Pull request by gabrirodd**

### CODE REVIEW

**Comment by Enchufa2** [comment]
There is no text in the article! Setting this PR as "draft", please click "Ready for review" again when the article is finished.

**Comment by gabrirodd** [comment]
Sorry, my mistake! It has been added with the text now.

**Review by Enchufa2 — APPROVED** [review]
Great work! The code was a bit messy... with a lot of repetitions. But it looks good after some cleanup.

**Comment by Enchufa2** [comment]
Published: https://csslab.uc3m.es/dataviz/projects/2022/100482798/

**Comment by gabrirodd** [comment]
Thanks for you help and the cleanup Iñaki!

It's just a little detail but I have noticed that the map uploaded to the dataviz platform is a bit different to the one in the output when I knit. The online map contains a little province with a NA and I explain in the article that there are no NAs in my version of the map.

Also, in the proyect archive in my front page it's only shown the first half of the map. Anyway, I don't know if it's my fault because of the way I pasted the two charts but just for you to know.

Regards!

**Comment by Enchufa2** [comment]
Yeap, there may be some small differences, because as you can see I refactored the categorisation a bit [here](https://github.com/IBiDat/dataviz/blob/e018843fe8a1280ca51027eb41e67417bec6c36e/_projects/2022/100482798/100482798.Rmd#L96-L113). I compared the numbers and there were small differences. It's possible that the manual categorisation was missing some issues. Anyway, it doesn't matter.

The front page cuts the images automatically so produce the thumbnails, so it depends on the size of the thumbnail, which depends on the size of the screen and the number of projects. So it is what it is. :)

**Comment by gabrirodd** [comment]
Okay, perfect. Thanks!

**Pull request merged**
