### PR TITLE
Final project- Alexandra Salo

### PR DESCRIPTION
**Pull request by alexandra-rose**

### CODE REVIEW

**Comment by Enchufa2** [comment]
Nicely done, thank you! I'll review it in the coming days.

**Comment by alexandra-rose** [comment]
Oops I made some more tiny changes, actually would maybe like to implement some ideas proposed in the presentation so I will close this for now!

**Comment by Enchufa2** [comment]
But leave it open! Your new changes will show up here.

**Comment by Enchufa2** [comment]
I converted it to draft. When this is ready for review, click in the corresponding button.

**Comment by Enchufa2** [comment]
Question: you marked this as ready, but you didn't push any changes since the last time, right? Are you planning on making any changes or is it ok as it is?

**Comment by alexandra-rose** [comment]
Hey!

I ended up not having the time to do the alterations I envisioned originally. So this is final now as is! Thanks, Alex

**Review by Enchufa2 — APPROVED** [review]
Great work! Merging after some cleanup.

**Comment by Enchufa2** [comment]
And here's your work, congrats! https://csslab.uc3m.es/dataviz/projects/2023/100508332/

**Pull request merged**
