### PR TITLE
Project - Phong Duong

### PR DESCRIPTION
**Pull request by phongtdng**

### CODE REVIEW

**Comment by phongtdng** [comment]
Hi @Enchufa2, I uploaded all the codes for the replication and alternative graph but no content for the alternative graph yet. Could you give suggestions for code in the mean time? Thank you so much!!!

**Review by Enchufa2 — COMMENTED** [review]
Looks good to me, great work! There are some code lines that are a bit too long (see the [deploy preview](https://deploy-preview-31--mucss-dataviz.netlify.app/_projects/2023/100507500/100507500.html)), and it seems there are some missing files under the `100507500_files` directory (see again the missing images in the preview).

Moving this to draft again, so that you can mark it as "ready for review" later.

**Comment by phongtdng** [comment]
> Looks good to me, great work! There are some code lines that are a bit too long (see the [deploy preview](https://deploy-preview-31--mucss-dataviz.netlify.app/_projects/2023/100507500/100507500.html)), and it seems there are some missing files under the `100507500_files` directory (see again the missing images in the preview).
> 
> Moving this to draft again, so that you can mark it as "ready for review" later.

I just added the missing files. I think it is fine now (at least from my computer?). And regarding for the long code, do you mean I should hide some of them?

**Review by Enchufa2 — APPROVED** [review]
Never mind... Merging with a few fixes, great work!

**Comment by Enchufa2** [comment]
And here's your work, congrats! https://csslab.uc3m.es/dataviz/projects/2023/100507500/

**Pull request merged**
