### PR TITLE
Project - María

### PR DESCRIPTION
**Pull request by mariajuradomillan**

### CODE REVIEW

**Comment by Enchufa2** [comment]
BTW, converting back to draft, because it's easier for me to look for green/gray in the PR list. Please click "ready for review" again when you want me to make another pass.

**Comment by Enchufa2** [comment]
Sorry, María, but I only see the graphs. You should commit and push everything inside the _projects directory. The Rmd is empty. Switching back to draft.

**Comment by mariajuradomillan** [comment]
Hola Iñaki, voy a intentarlo otra vez pero me dice que está todo actualizado
[image: image.png]

**Review by Enchufa2 — APPROVED** [review]
Great work! Merging with a few fixes.

**Comment by Enchufa2** [comment]
And here's your work: https://csslab.uc3m.es/dataviz/projects/2023/100430912/

**Pull request merged**
