### PR TITLE
Project Yassin Abdelhady

### PR DESCRIPTION
**Pull request by Yassinabdelhadyy**
Initial connection to dataviz repo :)

### CODE REVIEW

**Comment by Yassinabdelhadyy** [comment]
i have a question regarding the aside tag .. do you have it already styled when i deploy the html page; it isnt adjusted on my end but i can see the gap minder aside tag is well aligned so do i leave it as it is <aside> or do i write in line style for it ?

**Comment by Yassinabdelhadyy** [comment]
ohh and the heading tags "#" or "##" arent working also is the syntax in the Rmd wrong ?

**Comment by Yassinabdelhadyy** [comment]
> ohh and the heading tags "#" or "##" arent working also is the syntax in the Rmd wrong ?

it turned out to be syntax error i wasnt leaving a space after the "#" :D -- fixed it

**Comment by Enchufa2** [comment]
Great work! Apologies I didn't have time to answer the questions above, but merging now with some fixes.

**Comment by Enchufa2** [comment]
Here it is: https://csslab.uc3m.es/dataviz/projects/2022/100490068/

**Pull request merged**
