### PR TITLE
Project Laura Martinez

### PR DESCRIPTION
**Pull request by laura-martinez00**
Visual representation of the Brexit results

### CODE REVIEW

**Review by Enchufa2 — CHANGES_REQUESTED** [review]
The main file `100408925.Rmd` is empty! Please push the final one and let me know when this is ready again.

**Comment by laura-martinez00** [comment]
I pasted the code to the document. Nevertheless, the Rmd corresponding to that file on my computer had all the code in it!

**Comment by Enchufa2** [comment]
Maybe you are uploading files manually via the web interface instead of committing and pushing in RStudio?

Great job, some comments about the Rmd:

- The text is missing! I expect a short introduction where you present and show the selected graph. Then you should walk the reader throught the steps you take. See other projects for inspiration.
- Please remove numbering from headings to follow the general style of the projects section.
- Please remove packages that are not required (e.g. ggmap is not used, right?)
- Your figures are tall. Maybe you can play with the chunk figure options (height or aspect ratio) to make them look nicer?

If you added the last file via web browser, be sure to pull commits first in your RStudio git panel so that your local repo is in sync with GitHub and you can still push.

**Comment by laura-martinez00** [comment]
Sorry, pushed ready for review but it will be ready in a few hours, not yet

**Comment by laura-martinez00** [comment]
What I think is my final version of the project is uploaded

**Comment by laura-martinez00** [comment]
Screenshot 2024-01-19 at 01 18 52

**Comment by Enchufa2** [comment]
I think you committed but didn't hit "push" in the git panel, because there are no new commits here.

**Comment by laura-martinez00** [comment]
I think it should be now

**Comment by laura-martinez00** [comment]
Locally when I want to push the commits I keep on getting this issue: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

**Comment by Enchufa2** [comment]
Please run in the terminal panel in RStudio:

```
git log --oneline --graph -n10
```

and paste the output here

**Comment by laura-martinez00** [comment]
***@***.*** 100408925 % git log --oneline --graph -n10

*   29f1883 (*HEAD -> **main*) Merge branch 'main' of
https://github.com/laura-martinez00/dataviz

|\

| * 4ee87bc Update 100408925.Rmd

* | d6a3b30 Final RMD with text and enhacement

* | 713583a chunk settings

* | 8a3c182 commit final

* | b80ac95 (I´m not sure the commit I made yesterday appears on github)

* | 63dd573 Text and alternative representations added in this version

|/

* fd371a0 First upload of the code and the necessary files

* 18089dc Initial version of the project

* 6d0684a Initial version of the project

***@***.*** 100408925 %

**Comment by laura-martinez00** [comment]
(se ve mejor en el mail)

**Comment by Enchufa2** [comment]
Send me the Rmd by mail, please.

**Comment by Enchufa2** [comment]
I mean, directly to my uni email, not replying here, because I don't have email notifications enabled on GitHub.

**Review by Enchufa2 — APPROVED** [review]
Great work on the Rmd! The PR was a bit of a mess... ;-) But I've managed to rebuild it and clean thigs up. Merging with a few fixes.

**Comment by laura-martinez00** [comment]
Thank you! I know, I think it was because the projects branch appeared to me as duplicated and I pushed the Rmd in both folders one after another. That might have caused the issue. Thank you again!!

**Comment by Enchufa2** [comment]
Here's your work, congrats! https://csslab.uc3m.es/dataviz/projects/2023/100408925/

**Pull request merged**
