### PR TITLE
Project - Nadia Napolano

### PR DESCRIPTION
**Pull request by Nadian17**
i made changes from the first version, but i am not able to add them in the fork

### CODE REVIEW

**Comment by Nadian17** [comment]
hi, i hope it's okay. If i have done any mistake i'll fix it.

**Comment by Enchufa2** [comment]
The PR is empty, there's no Rmd. You also created files under the wrong directory. Please follow the tutorial: https://csslab.uc3m.es/dataviz/tutorials/project/

**Comment by Nadian17** [comment]
Does it work now?

**Comment by Enchufa2** [comment]
There was a commit before, but now it's gone.

**Pull request closed without merging**
